"""empty message

Revision ID: 991c83736bd5
Revises: c3bd4eb3ecab
Create Date: 2026-06-10 13:48:06.846099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991c83736bd5'
down_revision: Union[str, Sequence[str], None] = 'c3bd4eb3ecab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('access_rules_user_id_fkey'), 'access_rules', type_='foreignkey')
    op.drop_column('access_rules', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_rules', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('access_rules_user_id_fkey'), 'access_rules', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
